const token=document.querySelector('meta[name="spade65-token"]').content;
const $=id=>document.getElementById(id);
let meta=null,profile=null,currentLayer='normal',selectedKey=null,colorKeys=new Set(),activeMacro=0,activeAppLayer=0,animationTimer=null,animationPhase=0,streamBusy=false,audioContext=null,audioAnalyser=null,audioStream=null,layoutVariant=localStorage.getItem('spade65-layout')||'ansi-standard',recordingMacro=false,recordLast=0,recordPressed=new Set();
const subtitles={device:'Hardware overview and profile management',keymap:'Three-layer key assignment',lighting:'Built-in, per-key, and app streaming effects',macros:'Record and bind up to ten macros',settings:'Debounce, wireless timers, and safety',diagnostics:'Descriptors and feature coverage'};
const rows=[['esc','n1','n2','n3','n4','n5','n6','n7','n8','n9','n0','minus','plus','bksp'],['tab','q','w','e','r','t','y','u','i','o','p','lqu','rqu','k29','delete'],['caps','a','s','d','f','g','h','j','k','l','sem','quo','k42','enter','pageup'],['lshift','z','x','c','v','b','n','m','comma','dot','qmark','rshift','up','pagedown'],['lctrl','win','lalt','lspace','ralt','mspace','rspace','fn','rctrl','left','down','right']];
const titles={esc:'Esc',bksp:'Backspace',caps:'Caps',lshift:'L Shift',rshift:'R Shift',lctrl:'L Ctrl',rctrl:'R Ctrl',lalt:'L Alt',ralt:'R Alt',lspace:'Space',mspace:'Space',rspace:'Space',pageup:'Pg Up',pagedown:'Pg Dn',lqu:'[',rqu:']',sem:';',quo:"'",qmark:'/',comma:',',dot:'.',minus:'-',plus:'=',win:'Win',k29:'\\',k42:'\\'};
const isoPositions=[[70,21,35,35],[109,21,35,35],[148,21,35,35],[186,21,35,35],[226,21,35,35],[264,21,35,35],[303,21,35,35],[342,21,35,35],[381,21,35,35],[420,21,35,35],[458,21,35,35],[497,21,35,35],[536,21,35,35],[576,21,70,35],[70,61,55,35],[128,61,35,35],[168,61,35,35],[206,61,35,35],[245,61,35,35],[284,61,35,35],[323,61,35,35],[362,61,35,35],[400,61,35,35],[439,61,35,35],[478,61,35,35],[517,61,35,35],[556,61,35,35],[604,61,0,0],[652,61,35,35],[70,100,64,35],[138,100,35,35],[177,100,35,35],[215,100,35,35],[254,100,35,35],[293,100,35,35],[332,100,35,35],[371,100,35,35],[410,100,35,35],[448,100,35,35],[487,100,35,35],[526,100,35,35],[565,100,35,35],[606,61,41,74],[652,100,35,35],[70,138,83,35],[157,138,35,35],[196,138,35,35],[235,138,35,35],[274,138,35,35],[313,138,35,35],[352,138,35,35],[390,138,35,35],[430,138,35,35],[468,138,35,35],[507,138,35,35],[546,138,64,35],[614,138,35,35],[652,138,35,35],[70,177,45,35],[118,177,45,35],[167,177,45,35],[216,177,0,0],[303,177,0,0],[216,177,239,35],[352,177,0,0],[458,177,45,35],[507,177,45,35],[575,177,35,35],[614,177,35,35],[652,177,35,35]];
const ansiPositions=[[70,23,35,35],[109,23,35,35],[148,23,35,35],[186,23,35,35],[225,23,35,35],[264,23,35,35],[303,23,35,35],[342,23,35,35],[381,23,35,35],[420,23,35,35],[458,23,35,35],[497,23,35,35],[536,23,35,35],[577,23,70,35],[70,61,55,35],[128,61,35,35],[167,61,35,35],[206,61,35,35],[245,61,35,35],[284,61,35,35],[323,61,35,35],[362,61,35,35],[400,61,35,35],[439,61,35,35],[478,61,35,35],[517,61,35,35],[556,61,35,35],[595,61,54,35],[652,61,35,35],[70,100,65,35],[138,100,35,35],[177,100,35,35],[216,100,35,35],[255,100,35,35],[293,100,35,35],[332,100,35,35],[371,100,35,35],[410,100,35,35],[449,100,35,35],[488,100,35,35],[526,100,35,35],[548,100,0,0],[566,100,82,35],[652,100,35,35],[70,138,84,35],[158,138,35,35],[197,138,35,35],[235,138,35,35],[274,138,35,35],[313,138,35,35],[352,138,35,35],[391,138,35,35],[430,138,35,35],[468,138,35,35],[507,138,35,35],[546,138,64,35],[614,138,35,35],[652,138,35,35],[70,177,45,35],[118,177,45,35],[166,177,45,35],[216,177,0,0],[303,177,0,0],[216,177,239,35],[353,177,0,0],[459,177,45,35],[507,177,45,35],[575,177,35,35],[614,177,35,35],[652,177,35,35]];
const splitPositions={iso:{61:[216,177,82,35],62:[303,177,45,35],63:[216,177,0,0],64:[352,177,102,35]},ansi:{61:[216,177,82,35],62:[303,177,45,35],63:[216,177,0,0],64:[353,177,103,35]}};
function keyPosition(index){const family=layoutVariant.startsWith('iso')?'iso':'ansi',positions=family==='iso'?isoPositions:ansiPositions;if(layoutVariant.endsWith('split')&&splitPositions[family][index])return splitPositions[family][index];return positions[index]}

async function api(action,data={},method='POST'){
  const options={method,headers:{'X-Spade65-Token':token}};
  if(method==='POST'){options.headers['Content-Type']='application/json';options.body=JSON.stringify(data)}
  const response=await fetch(`/api/${action}`,options);const result=await response.json();
  if(!response.ok||result.ok===false)throw new Error(result.error||`HTTP ${response.status}`);return result;
}
function toast(message,error=false){const el=$('toast');el.textContent=message;el.className=`show${error?' error':''}`;clearTimeout(el._timer);el._timer=setTimeout(()=>el.className='',3500)}
function device(){return $('deviceSelect').value||null}
function actionPayload(extra={}){return{device:device(),...extra}}
function storedProfiles(){try{const value=JSON.parse(localStorage.getItem('spade65-profiles')||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch{return{}}}
function renderSavedProfiles(selected=''){const select=$('savedProfile'),items=storedProfiles();select.innerHTML='<option value="">Unsaved profile</option>';Object.keys(items).sort().forEach(name=>{const option=document.createElement('option');option.value=name;option.textContent=name;select.append(option)});select.value=selected}
async function loadSavedProfile(name){if(!name)return;try{const item=storedProfiles()[name];await api('validate',{profile:item});profile=structuredClone(item);$('profileName').value=name;selectedKey=null;activeMacro=0;activeAppLayer=0;renderKeyboard();renderColorKeyboard();renderMacros();renderAppLayers();toast(`${name} loaded`)}catch(error){toast(error.message,true)}}
async function saveProfile(){try{await api('validate',{profile});const name=$('profileName').value.trim();if(!name)return toast('Profile name is required',true);const items=storedProfiles();items[name]=structuredClone(profile);localStorage.setItem('spade65-profiles',JSON.stringify(items));renderSavedProfiles(name);toast(`${name} saved locally`)}catch(error){toast(error.message,true)}}
function deleteSavedProfile(){const name=$('savedProfile').value;if(!name)return toast('Select a saved profile first',true);if(!confirm(`Delete local profile ${name}?`))return;const items=storedProfiles();delete items[name];localStorage.setItem('spade65-profiles',JSON.stringify(items));renderSavedProfiles();toast(`${name} deleted`)}

async function refresh(){try{meta=await api('status',{},'GET');if(!profile)profile=structuredClone(meta.profile);renderDevices();renderEffects();renderUsageList();renderSavedProfiles($('savedProfile').value);renderKeyboard();renderColorKeyboard();renderMacros();renderAppLayers();renderDiagnostics();$('connectionDot').classList.toggle('online',meta.devices.length>0);$('connectionText').textContent=meta.devices.length?`${meta.devices[0].name} connected`:'No device';$('transportBadge').textContent=meta.devices.length?`${meta.devices[0].transport} ${meta.devices[0].vid}:${meta.devices[0].pid}`:'Not connected';$('descriptorBadge').textContent=meta.devices.some(d=>d.reports.some(r=>r.kind==='feature'&&r.id===7&&r.bytes===620))?'Descriptor verified':'Config interface unavailable'}catch(error){toast(error.message,true)}}
function renderDevices(){const select=$('deviceSelect'),old=select.value;select.innerHTML='';for(const item of meta.devices.filter(d=>d.usages.includes('ff02:0001'))){const o=document.createElement('option');o.value=item.path;o.textContent=`${item.name} · ${item.transport} · ${item.path}`;select.append(o)}if([...select.options].some(o=>o.value===old))select.value=old}
function renderEffects(){if($('effectSelect').options.length)return;for(const effect of meta.effects){const o=document.createElement('option');o.value=effect;o.textContent=effect.replaceAll('-',' ');$('effectSelect').append(o)}$('effectSelect').value='fixed'}
function renderUsageList(){const list=$('usageList'),preset=$('usagePreset');list.innerHTML='';preset.innerHTML='<option value="">Choose keyboard/media/mouse function…</option>';for(const name of Object.keys(meta.usages).sort()){const o=document.createElement('option');o.value=name;list.append(o)}for(const [group,names] of Object.entries(meta.usage_groups)){const optgroup=document.createElement('optgroup');optgroup.label=group;for(const name of names){const option=document.createElement('option');option.value=name;option.textContent=`${name} · 0x${meta.usages[name].toString(16).padStart(2,'0')}`;optgroup.append(option)}preset.append(optgroup)}}
function keyLabel(key){return titles[key]||key.replace(/^n(?=\d)/,'')}
function buildKeyboard(container,mode){container.innerHTML='';rows.flat().forEach((key,index)=>{const [x,y,w,h]=keyPosition(index);if(!w||!h)return;const b=document.createElement('button');b.className='key';b.dataset.key=key;b.style.cssText=`--x:${x/7.57}%;--y:${y/2.36}%;--w:${w/7.57}%;--h:${h/2.36}%`;b.textContent=keyLabel(key);if(mode==='assign'&&profile.layers[currentLayer][key])b.classList.add('assigned');if(mode==='assign'&&selectedKey===key)b.classList.add('selected');if(mode==='color'&&colorKeys.has(key))b.classList.add('selected');if(mode==='color'&&profile.colors[key]){const sw=document.createElement('i');sw.className='swatch';const c=profile.colors[key];sw.style.background=Array.isArray(c)?`rgb(${c.join(',')})`:c;b.append(sw)}b.onclick=()=>mode==='assign'?selectKey(key):toggleColorKey(key);container.append(b)})}
function profileSettings(){if(!profile.settings||typeof profile.settings!=='object')profile.settings={win_lock:false,wasd_arrows:false};return profile.settings}
function renderKeyboard(){buildKeyboard($('keyboard'),'assign');renderLayerSummary();$('winLock').checked=!!profileSettings().win_lock;$('wasdArrows').checked=!!profileSettings().wasd_arrows;if(selectedKey)loadAssignment()}
function renderColorKeyboard(){buildKeyboard($('colorKeyboard'),'color');renderAppRangeSummary()}
function selectKey(key){selectedKey=key;$('selectedKey').textContent=keyLabel(key);renderKeyboard()}
function toggleColorKey(key){colorKeys.has(key)?colorKeys.delete(key):colorKeys.add(key);renderColorKeyboard()}
function loadAssignment(){const value=profile.layers[currentLayer][selectedKey];document.querySelectorAll('#modifierWrap input').forEach(x=>x.checked=false);if(value===undefined){$('assignmentType').value='default';$('usageInput').value=''}else if(typeof value==='object'&&'macro'in value){$('assignmentType').value='macro';$('macroAssign').value=value.macro}else{$('assignmentType').value='usage';$('usageInput').value=typeof value==='object'?value.usage:value;const mods=typeof value==='object'?(value.modifiers||0):0;document.querySelectorAll('#modifierWrap input').forEach(x=>x.checked=!!(mods&Number(x.value)))}assignmentTypeChanged()}
function assignmentTypeChanged(){const type=$('assignmentType').value;$('usageWrap').hidden=type!=='usage';$('modifierWrap').hidden=type!=='usage';$('macroWrap').hidden=type!=='macro'}
function saveAssignment(){if(!selectedKey)return toast('Select a key first',true);const type=$('assignmentType').value;if(type==='default')delete profile.layers[currentLayer][selectedKey];else if(type==='macro'){if(!profile.macros.length)return toast('Create a macro first',true);profile.layers[currentLayer][selectedKey]={macro:Number($('macroAssign').value)}}else{const usage=$('usageInput').value.trim();if(!usage)return toast('Usage is required',true);let modifiers=0;document.querySelectorAll('#modifierWrap input:checked').forEach(x=>modifiers|=Number(x.value));profile.layers[currentLayer][selectedKey]=modifiers?{usage,modifiers}:usage}renderKeyboard();toast(`${keyLabel(selectedKey)} saved on ${currentLayer}`)}
function renderLayerSummary(){const box=$('layerSummary');box.innerHTML='';for(const layer of ['normal','fn1','fn2']){const div=document.createElement('div');div.textContent=`${layer.toUpperCase()}: ${Object.keys(profile.layers[layer]).length} assignments`;box.append(div)}const div=document.createElement('div');div.textContent=`Colors: ${Object.keys(profile.colors).length}`;box.append(div)}
function backupKeys(name,keys){const settings=profileSettings();settings[name]={};for(const key of keys)settings[name][key]=Object.hasOwn(profile.layers.normal,key)?{present:true,value:structuredClone(profile.layers.normal[key])}:{present:false}}
function restoreKeys(name){const settings=profileSettings(),backup=settings[name]||{};for(const [key,item] of Object.entries(backup))item.present?profile.layers.normal[key]=item.value:delete profile.layers.normal[key];delete settings[name]}
function toggleWinLock(enabled){const settings=profileSettings();if(enabled&&!settings.win_lock){backupKeys('win_lock_backup',['win']);profile.layers.normal.win='disabled'}else if(!enabled&&settings.win_lock)restoreKeys('win_lock_backup');settings.win_lock=enabled;renderKeyboard();toast(enabled?'Win key disabled in profile':'Win key restored')}
function toggleWasdArrows(enabled){const settings=profileSettings(),keys=['w','a','s','d','up','left','down','right'];if(enabled&&!settings.wasd_arrows){backupKeys('wasd_arrows_backup',keys);Object.assign(profile.layers.normal,{w:'up',a:'left',s:'down',d:'right',up:'w',left:'a',down:'s',right:'d'})}else if(!enabled&&settings.wasd_arrows)restoreKeys('wasd_arrows_backup');settings.wasd_arrows=enabled;renderKeyboard();toast(enabled?'WASD and arrows swapped in profile':'WASD and arrows restored')}
function disableGroup(group){const groups={numbers:['n0','n1','n2','n3','n4','n5','n6','n7','n8','n9'],letters:[...'abcdefghijklmnopqrstuvwxyz'],symbols:['minus','plus','lqu','rqu','k29','k42','sem','quo','comma','dot','qmark'],controls:['esc','bksp','tab','caps','enter','delete','pageup','pagedown','lshift','rshift','lctrl','rctrl','lalt','ralt','win','fn','up','down','left','right','lspace','mspace','rspace'],all:meta.buttons};for(const key of groups[group])profile.layers[currentLayer][key]='disabled';renderKeyboard();toast(`${group} disabled on ${currentLayer}`)}
function undoDisabled(){for(const [key,value] of Object.entries(profile.layers[currentLayer]))if(value==='disabled'||value===0)delete profile.layers[currentLayer][key];renderKeyboard();toast(`Disabled assignments removed from ${currentLayer}`)}

function newAppLayer(){return{mode:'wave',enabled:true,speed:5,opacity:100,bandwidth:200,angle:0,number:5,gap:0,fire:1,center_x:0,center_y:0,gradient:true,reverse:false,bump:false,bidirectional:false,audio:false,colors:['#ff0000','#00ffff','#8000ff'],keys:[]}}
function appLayers(){const settings=profileSettings();if(!Array.isArray(settings.app_effects)||!settings.app_effects.length)settings.app_effects=[newAppLayer()];settings.app_effects=settings.app_effects.slice(0,10).map(value=>{const layer=value&&typeof value==='object'&&!Array.isArray(value)?{...newAppLayer(),...value}:newAppLayer();layer.keys=Array.isArray(layer.keys)?layer.keys.filter(key=>meta?.buttons.includes(key)):[];layer.colors=Array.isArray(layer.colors)?layer.colors.slice(0,20).filter(color=>/^#[0-9a-f]{6}$/i.test(color)):[];if(!layer.colors.length)layer.colors=newAppLayer().colors;return layer});return settings.app_effects}
function appLayer(){activeAppLayer=Math.min(activeAppLayer,appLayers().length-1);return appLayers()[activeAppLayer]}
function renderAppLayers(){const list=$('appLayerList');list.innerHTML='';appLayers().forEach((layer,index)=>{const row=document.createElement('div');row.className=`effect-layer${index===activeAppLayer?' active':''}`;const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=layer.enabled!==false;enabled.title='Show/hide layer';enabled.onclick=event=>event.stopPropagation();enabled.onchange=()=>layer.enabled=enabled.checked;const name=document.createElement('button');name.textContent=`${index+1} · ${(layer.mode||'wave').replaceAll('-',' ')}`;name.onclick=()=>{activeAppLayer=index;renderAppLayers();loadAppLayer()};row.append(enabled,name);list.append(row)});$('removeAppLayerBtn').disabled=appLayers().length<=1;loadAppLayer()}
function loadAppLayer(){const layer=appLayer();$('animation').value=layer.mode;$('appSpeed').value=layer.speed;$('appSpeedOut').value=layer.speed;$('appOpacity').value=layer.opacity;$('appOpacityOut').value=layer.opacity;$('appBandwidth').value=layer.bandwidth;$('appBandwidthOut').value=layer.bandwidth;$('appAngle').value=layer.angle;$('appAngleOut').value=layer.angle;$('appNumber').value=layer.number;$('appGap').value=layer.gap;$('appFire').value=layer.fire;$('appCenterX').value=layer.center_x;$('appCenterY').value=layer.center_y;$('appGradient').checked=layer.gradient!==false;$('appReverse').checked=!!layer.reverse;$('appBump').checked=!!layer.bump;$('appBidirectional').checked=!!layer.bidirectional;$('audioSync').checked=!!layer.audio;document.querySelectorAll('.app-color').forEach((input,index)=>input.value=layer.colors?.[index]||'#000000');renderAppRangeSummary()}
function saveAppLayer(){const layer=appLayer();layer.mode=$('animation').value;layer.speed=Number($('appSpeed').value);layer.opacity=Number($('appOpacity').value);layer.bandwidth=Number($('appBandwidth').value);layer.angle=Number($('appAngle').value);layer.number=Number($('appNumber').value);layer.gap=Number($('appGap').value);layer.fire=Number($('appFire').value);layer.center_x=Number($('appCenterX').value);layer.center_y=Number($('appCenterY').value);layer.gradient=$('appGradient').checked;layer.reverse=$('appReverse').checked;layer.bump=$('appBump').checked;layer.bidirectional=$('appBidirectional').checked;layer.audio=$('audioSync').checked;layer.colors=[...document.querySelectorAll('.app-color')].map(input=>input.value);renderAppLayers()}
function addAppLayer(){if(appLayers().length>=10)return toast('Maximum 10 app-effect layers',true);appLayers().push(newAppLayer());activeAppLayer=appLayers().length-1;renderAppLayers();toast('App-effect layer added')}
function removeAppLayer(){if(appLayers().length<=1)return;appLayers().splice(activeAppLayer,1);activeAppLayer=Math.max(0,activeAppLayer-1);renderAppLayers();toast('App-effect layer removed')}
function setAppRange(){appLayer().keys=[...colorKeys];renderAppRangeSummary();toast(colorKeys.size?`Effect limited to ${colorKeys.size} keys`:'Effect applies to all keys')}
function clearAppRange(){appLayer().keys=[];renderAppRangeSummary();toast('Effect applies to all keys')}
function renderAppRangeSummary(){const target=$('appRangeSummary');if(!target||!profile)return;const keys=appLayer().keys||[];target.textContent=keys.length?`Current layer range: ${keys.length} selected keys`:'Current layer range: all keys'}

function renderMacros(){const list=$('macroList');list.innerHTML='';profile.macros.forEach((macro,i)=>{const b=document.createElement('button');b.className=i===activeMacro?'active':'';b.textContent=`M${macro.index} · ${macro.name||'Macro'} (${macro.events.length})`;b.onclick=()=>{if(recordingMacro)stopMacroRecording();activeMacro=i;renderMacros()};list.append(b)});const macro=profile.macros[activeMacro];$('macroTitle').textContent=macro?`M${macro.index} · ${macro.name||'Macro'}`:'Macro editor';$('macroName').value=macro?.name??'';$('macroRepeat').value=macro?.repeat??1;$('eventList').innerHTML='';if(macro)macro.events.forEach((event,i)=>renderEvent(event,i));$('deleteMacroBtn').disabled=!macro;$('addEventBtn').disabled=!macro;$('recordMacroBtn').disabled=!macro;$('recordMacroBtn').textContent=recordingMacro?'■ Stop recording':'● Record';renderMacroAssign()}
function renderMacroAssign(){const s=$('macroAssign');s.innerHTML='';for(const macro of profile.macros){const o=document.createElement('option');o.value=macro.index;o.textContent=`M${macro.index} · ${macro.name||'Macro'}`;s.append(o)}}
function renderEvent(event,index){const row=document.createElement('div');row.className='event';const delay=document.createElement('input');delay.type='number';delay.min=0;delay.max=32767;delay.value=event.delay_ms;delay.onchange=()=>event.delay_ms=Number(delay.value);const usage=document.createElement('input');usage.value=event.usage;usage.setAttribute('list','usageList');usage.onchange=()=>event.usage=usage.value;const state=document.createElement('select');state.innerHTML='<option value="true">Key down</option><option value="false">Key up</option>';state.value=String(event.pressed);state.onchange=()=>event.pressed=state.value==='true';const del=document.createElement('button');del.textContent='×';del.className='danger';del.onclick=()=>{profile.macros[activeMacro].events.splice(index,1);renderMacros()};row.append(delay,usage,state,del);$('eventList').append(row)}
function addMacro(){if(profile.macros.length>=10)return toast('Maximum 10 macros',true);const used=new Set(profile.macros.map(m=>m.index));let index=0;while(used.has(index))index++;profile.macros.push({index,name:`Macro ${index}`,repeat:1,events:[]});activeMacro=profile.macros.length-1;renderMacros()}
function deleteMacro(){const macro=profile.macros[activeMacro];if(!macro)return;for(const layer of Object.values(profile.layers))for(const [key,value] of Object.entries(layer))if(typeof value==='object'&&value.macro===macro.index)delete layer[key];profile.macros.splice(activeMacro,1);activeMacro=Math.max(0,activeMacro-1);renderMacros();renderKeyboard()}
function addEvent(){const macro=profile.macros[activeMacro];if(!macro)return;if(macro.events.length>=84)return toast('Maximum 84 events',true);macro.events.push({delay_ms:20,usage:'a',pressed:macro.events.length%2===0});renderMacros()}
function eventUsage(event){if(event.code.startsWith('Key'))return event.code.slice(3).toLowerCase();if(event.code.startsWith('Digit'))return event.code.slice(5);if(/^F\d+$/.test(event.code))return event.code.toLowerCase();return{Enter:'enter',Escape:'esc',Backspace:'backspace',Tab:'tab',Space:'space',Minus:'minus',Equal:'equal',BracketLeft:'left-bracket',BracketRight:'right-bracket',Backslash:'backslash',Semicolon:'semicolon',Quote:'quote',Backquote:'grave',Comma:'comma',Period:'dot',Slash:'slash',CapsLock:'caps-lock',PrintScreen:'print-screen',ScrollLock:'scroll-lock',Pause:'pause',Insert:'insert',Home:'home',PageUp:'page-up',Delete:'delete',End:'end',PageDown:'page-down',ArrowRight:'right',ArrowLeft:'left',ArrowDown:'down',ArrowUp:'up',ControlLeft:'left-ctrl',ShiftLeft:'left-shift',AltLeft:'left-alt',MetaLeft:'left-gui',ControlRight:'right-ctrl',ShiftRight:'right-shift',AltRight:'right-alt',MetaRight:'right-gui'}[event.code]||null}
function recordMacroEvent(event){if(!recordingMacro||event.repeat)return;const usage=eventUsage(event);if(!usage)return;const isDown=event.type==='keydown';if(isDown&&recordPressed.has(event.code)||!isDown&&!recordPressed.has(event.code))return;isDown?recordPressed.add(event.code):recordPressed.delete(event.code);const macro=profile.macros[activeMacro];if(macro.events.length>=84){stopMacroRecording();return toast('Maximum 84 events reached',true)}const now=performance.now();macro.events.push({delay_ms:Math.max(0,Math.round(now-recordLast)),usage,pressed:isDown});recordLast=now;event.preventDefault();renderMacros()}
function startMacroRecording(){const macro=profile.macros[activeMacro];if(!macro)return;if(macro.events.length&&!confirm('Clear current events and record a new macro?'))return;macro.events=[];recordPressed.clear();recordLast=performance.now();recordingMacro=true;document.addEventListener('keydown',recordMacroEvent,true);document.addEventListener('keyup',recordMacroEvent,true);renderMacros();toast('Recording keyboard events… click Stop when finished')}
function stopMacroRecording(){recordingMacro=false;recordPressed.clear();document.removeEventListener('keydown',recordMacroEvent,true);document.removeEventListener('keyup',recordMacroEvent,true);renderMacros();toast('Macro recording stopped')}
function toggleMacroRecording(){recordingMacro?stopMacroRecording():startMacroRecording()}

async function doAction(action,payload,success){try{await api(action,actionPayload(payload));toast(success)}catch(error){toast(error.message,true)}}
async function applyProfile(){if(!confirm('This writes all three keymap layers and macros. Continue?'))return;if(prompt('Type APPLY PROFILE to continue')!=='APPLY PROFILE')return toast('Cancelled',true);await doAction('profile',{profile,confirmation:'APPLY PROFILE'},'Profile applied')}
function exportProfile(){const blob=new Blob([JSON.stringify(profile,null,2)+'\n'],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${$('profileName').value||'spade65-profile'}.json`;a.click();URL.revokeObjectURL(a.href)}
function importProfile(file){const reader=new FileReader();reader.onload=async()=>{try{const data=JSON.parse(reader.result);await api('validate',{profile:data});profile=data;selectedKey=null;activeMacro=0;activeAppLayer=0;renderKeyboard();renderColorKeyboard();renderMacros();renderAppLayers();toast('Profile imported and validated')}catch(error){toast(error.message,true)}};reader.readAsText(file)}
function newProfile(){if(!confirm('Discard the current in-memory profile?'))return;profile=structuredClone(meta.profile);selectedKey=null;colorKeys.clear();activeMacro=0;activeAppLayer=0;renderKeyboard();renderColorKeyboard();renderMacros();renderAppLayers();toast('New profile created')}

function setSelectedColor(){if(!colorKeys.size)return toast('Select at least one key',true);for(const key of colorKeys)profile.colors[key]=$('colorPicker').value;renderColorKeyboard();renderLayerSummary();toast(`Color stored for ${colorKeys.size} keys`)}
function clearColors(){profile.colors={};colorKeys.clear();renderColorKeyboard();renderLayerSummary()}
async function streamFrame(){if(streamBusy)return;streamBusy=true;try{await api('stream',actionPayload({profile}))}catch(error){stopAnimation();toast(error.message,true)}finally{streamBusy=false}}
function audioLevel(){if(!audioAnalyser)return 0;const data=new Uint8Array(audioAnalyser.frequencyBinCount);audioAnalyser.getByteFrequencyData(data);return data.reduce((sum,n)=>sum+n,0)/(data.length*255)}
async function startAudio(){if(audioAnalyser)return;audioStream=await navigator.mediaDevices.getUserMedia({audio:true});audioContext=new AudioContext();const source=audioContext.createMediaStreamSource(audioStream);audioAnalyser=audioContext.createAnalyser();audioAnalyser.fftSize=256;source.connect(audioAnalyser)}
function stopAudio(){if(audioStream)audioStream.getTracks().forEach(track=>track.stop());if(audioContext)audioContext.close();audioStream=null;audioContext=null;audioAnalyser=null}
function hexRgb(value){const hex=value.replace('#','');return[0,2,4].map(offset=>parseInt(hex.slice(offset,offset+2),16))}
function paletteRgb(colors,position,gradient=true){const palette=(colors?.length?colors:['#ff0000']).map(hexRgb);if(!gradient||palette.length===1)return palette[0];const scaled=((position%1)+1)%1*(palette.length-1),index=Math.floor(scaled),amount=scaled-index,next=Math.min(index+1,palette.length-1);return palette[index].map((value,channel)=>Math.round(value+(palette[next][channel]-value)*amount))}
function blendRgb(base,top,alpha){return base.map((value,index)=>Math.round(value*(1-alpha)+top[index]*alpha))}
function layerPixel(layer,key,x,y,index,level){if(layer.enabled===false||(layer.keys?.length&&!layer.keys.includes(key)))return null;const speed=Number(layer.speed||1),phase=animationPhase*speed,direction=(layer.reverse?-1:1)*(layer.bidirectional&&y%2?-1:1),dx=x-6.5-Number(layer.center_x||0),dy=y-2-Number(layer.center_y||0),angle=(Math.atan2(dy,dx)*180/Math.PI+360+Number(layer.angle||0))%360,distance=Math.sqrt(dx*dx+dy*dy),band=200/Math.max(50,Number(layer.bandwidth||200)),gap=Number(layer.gap||0)/100,density=Math.max(1,Number(layer.number||5));let position=0.95,light=1;if(layer.mode==='wave')position=(Math.sin((x*band+direction*phase/8)+gap)+1)/2;else if(layer.mode==='conic')position=(angle+direction*phase*2)%360/360;else if(layer.mode==='spiral')position=(angle+distance*35*band+direction*phase*2)%360/360;else if(layer.mode==='cycle')position=(index/70+direction*phase/120)%1;else if(layer.mode==='linear-wave')position=(x*band/8+y/14+Number(layer.angle||0)/360+direction*phase/100+gap)%1;else if(layer.mode==='ripple')position=(distance*band/5-direction*phase/80+gap)%1;else if(layer.mode==='breathe'){position=0;light=.25+.75*(1+Math.sin(phase/18))/2}else if(layer.mode==='rain'){position=.55;light=((x*19+y*37+direction*phase*density)%100)>100-density*6?1:.08}else if(layer.mode==='fire'){position=Math.random()*.14;light=.25+Math.random()*.06*Math.max(1,Number(layer.fire||1))}else if(layer.mode==='trigger'){position=.95;light=((index*31+phase*3)%97)>90?1:.08}if(layer.bump)light*=1-Math.abs((((position%1)+1)%1)*2-1);if(layer.audio)light*=Math.min(1,level*4);const color=paletteRgb(layer.colors,position,layer.gradient!==false),alpha=Math.max(0,Math.min(1,Number(layer.opacity??100)/100*light));return{color,alpha}}
function animateColors(){const level=audioLevel(),layers=appLayers();let index=0;rows.forEach((row,y)=>row.forEach((key,x)=>{let output=[0,0,0];for(const layer of layers){const pixel=layerPixel(layer,key,x,y,index,level);if(pixel)output=blendRgb(output,pixel.color,pixel.alpha)}profile.colors[key]='#'+output.map(value=>value.toString(16).padStart(2,'0')).join('');index++}));animationPhase+=1;renderColorKeyboard();streamFrame()}
function hsl(h,s,l){s/=100;l/=100;const k=n=>(n+h/30)%12,a=s*Math.min(l,1-l),f=n=>l-a*Math.max(-1,Math.min(k(n)-3,Math.min(9-k(n),1)));return'#'+[f(0),f(8),f(4)].map(x=>Math.round(255*x).toString(16).padStart(2,'0')).join('')}
async function toggleAnimation(){if(animationTimer)return stopAnimation();try{saveAppLayer();if(appLayers().some(layer=>layer.enabled!==false&&layer.audio))await startAudio();$('animationBtn').textContent='Stop animation';animationTimer=setInterval(animateColors,1000/Number($('fps').value));animateColors()}catch(error){stopAudio();toast(`Audio unavailable: ${error.message}`,true)}}
function stopAnimation(){clearInterval(animationTimer);animationTimer=null;stopAudio();$('animationBtn').textContent='Start animation'}
function renderDiagnostics(){$('deviceJson').textContent=JSON.stringify(meta.devices,null,2)}

document.querySelectorAll('#nav button').forEach(button=>button.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(`page-${button.dataset.page}`).classList.add('active');$('pageTitle').textContent=button.textContent;$('pageSubtitle').textContent=subtitles[button.dataset.page]});
document.querySelectorAll('#layerTabs button').forEach(button=>button.onclick=()=>{currentLayer=button.dataset.layer;document.querySelectorAll('#layerTabs button').forEach(x=>x.classList.toggle('active',x===button));renderKeyboard()});
$('layoutVariant').value=layoutVariant;$('layoutVariant').onchange=e=>{layoutVariant=e.target.value;localStorage.setItem('spade65-layout',layoutVariant);renderKeyboard();renderColorKeyboard()};
$('refreshBtn').onclick=refresh;$('assignmentType').onchange=assignmentTypeChanged;$('usagePreset').onchange=e=>{if(e.target.value)$('usageInput').value=e.target.value};$('assignBtn').onclick=saveAssignment;$('winLock').onchange=e=>toggleWinLock(e.target.checked);$('wasdArrows').onchange=e=>toggleWasdArrows(e.target.checked);document.querySelectorAll('.disable-group').forEach(button=>button.onclick=()=>disableGroup(button.dataset.group));$('undoDisableBtn').onclick=undoDisabled;$('newProfileBtn').onclick=newProfile;$('saveProfileBtn').onclick=saveProfile;$('deleteProfileBtn').onclick=deleteSavedProfile;$('savedProfile').onchange=e=>loadSavedProfile(e.target.value);$('exportProfileBtn').onclick=exportProfile;$('importProfileBtn').onclick=()=>$('profileFile').click();$('profileFile').onchange=e=>e.target.files[0]&&importProfile(e.target.files[0]);$('applyProfileBtn').onclick=applyProfile;
$('brightness').oninput=e=>$('brightnessOut').value=e.target.value;$('speed').oninput=e=>$('speedOut').value=e.target.value;
$('appSpeed').oninput=e=>{$('appSpeedOut').value=e.target.value;saveAppLayer()};$('appOpacity').oninput=e=>{$('appOpacityOut').value=e.target.value;saveAppLayer()};$('appBandwidth').oninput=e=>{$('appBandwidthOut').value=e.target.value;saveAppLayer()};$('appAngle').oninput=e=>{$('appAngleOut').value=e.target.value;saveAppLayer()};
$('animation').onchange=saveAppLayer;for(const id of ['appNumber','appGap','appFire','appCenterX','appCenterY','appGradient','appReverse','appBump','appBidirectional','audioSync'])$(id).onchange=saveAppLayer;document.querySelectorAll('.app-color').forEach(input=>input.oninput=saveAppLayer);$('addAppLayerBtn').onclick=addAppLayer;$('removeAppLayerBtn').onclick=removeAppLayer;$('setAppRangeBtn').onclick=setAppRange;$('clearAppRangeBtn').onclick=clearAppRange;
$('applyEffectBtn').onclick=()=>doAction('rgb',{effect:$('effectSelect').value,brightness:Number($('brightness').value),speed:Number($('speed').value),color_index:Number($('colorIndex').value),multicolor:$('multicolor').checked},'Built-in effect applied');
$('setColorBtn').onclick=setSelectedColor;$('clearColorsBtn').onclick=clearColors;$('applyColorsBtn').onclick=()=>doAction('per-key',{profile,brightness:Number($('brightness').value),speed:Number($('speed').value)},'Per-key colors applied');$('streamOnceBtn').onclick=()=>{saveAppLayer();animateColors()};$('animationBtn').onclick=toggleAnimation;
$('addMacroBtn').onclick=addMacro;$('deleteMacroBtn').onclick=deleteMacro;$('addEventBtn').onclick=addEvent;$('recordMacroBtn').onclick=toggleMacroRecording;$('macroName').onchange=e=>{if(profile.macros[activeMacro]){profile.macros[activeMacro].name=e.target.value.trim()||`Macro ${profile.macros[activeMacro].index}`;renderMacros()}};$('macroRepeat').onchange=e=>{if(profile.macros[activeMacro])profile.macros[activeMacro].repeat=Number(e.target.value)};
$('debounceBtn').onclick=()=>doAction('debounce',{milliseconds:Number($('debounce').value)},'Debounce applied');$('sleepBtn').onclick=()=>doAction('sleep',{light_off:Number($('lightOff').value),hibernate:Number($('hibernate').value)},'Wireless timers applied');$('resetBtn').onclick=()=>doAction('reset',{confirmation:$('resetText').value},'Device reset sent');
$('validateBtn').onclick=async()=>{try{const result=await api('validate',{profile});$('validationOutput').textContent=JSON.stringify(result,null,2);toast('Profile is valid')}catch(error){$('validationOutput').textContent=error.message;toast(error.message,true)}};
refresh();
const initialPage=location.hash.slice(1);if(initialPage&&subtitles[initialPage])document.querySelector(`#nav button[data-page="${initialPage}"]`).click();
